services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: apyvyra
      POSTGRES_PASSWORD: apyvyra
      POSTGRES_DB: apyvyra
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Database=apyvyra;Username=apyvyra;Password=apyvyra"
      ASPNETCORE_URLS: "http://*:5000"
      Jwt__Key: "YourSuperSecretKeyThatIsAtLeast32CharactersLongForHS256"
      Jwt__Issuer: "ApyvyraAPI"
      Jwt__Audience: "ApyvyraClient"
      Jwt__ExpiresInMinutes: "60"
      EmailSettings__SmtpServer: "smtp.gmail.com"
      EmailSettings__SmtpPort: "587"
      EmailSettings__Username: "your-email@gmail.com"
      EmailSettings__Password: "your-app-password"
      EmailSettings__FromEmail: "your-email@gmail.com"
      EmailSettings__FromName: "Apyvyra"
      EmailSettings__EnableSsl: "true"
      EmailSettings__DevelopmentMode: "true"
      BaseUrl: "http://localhost:8080"
      QuerySettings__MAX_RECORDS_QUERIES_COUNT: "100"
      Localization__Language: "en-US"
      Localization__ResourcePath: "Resources/Translations"
      AllowedHosts: "*"
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  db_data:
